*
▪ * Team Id:  eYRC#3575
▪ * Author List: AMAN KUMAR YADAV , SATYA PRAKASH MALLICK AND SAMIKSHA SAHU 
▪ * Filename: 5_MOTORS
▪ * Theme: KrishiBalancer (KB)
▪ * Functions: setup() , loop() , FINAL_PWM_SENT( )
▪ * Global Variables: FINAL_PWM_SENT_TO_MOTOR_1 , FINAL_PWM_SENT_TO_MOTOR_2
*/ 


/*MOTOR DRIVER CONFIGURATION */
#define EN_A 6    // PWM SIGNAL FOR CONTROLLING SPEED OF MOTOR_1
#define EN_B 5    // PWM SIGNAL FOR CONTROLLING SPEED OF MOTOR_2

#define IN_1 A2   // IN_1 AND IN_2 ARE USED TO CONTROL THE DIRECTION OF MOTOR_1
#define IN_2 A3

#define IN_3 9    // IN_3 AND IN_4 ARE USED TO CONTROL THE DIRECTION OF MOTOR_2
#define IN_4 4   


volatile int FINAL_PWM_SENT_TO_MOTOR_1 = 0  ;  // FINAL PWM SIGNAL(0-255) SENT TO MOTOR_1 
volatile int FINAL_PWM_SENT_TO_MOTOR_2 = 0  ;  // FINAL PWM SIGNAL(0-255) SENT TO MOTOR_2



/****************************************************************************************************
* Function Name: FINAL_PWM_SENT()
* Input:  pwm signal to MOTOR_1 , pwm signal to MOTOR_2
* Output: NONE
* Logic:  USED TO CONTROL THE MOTORS USING THE PWM SIGNAL GENERATED BY THE PID CONTROLLER.
* Example Call : FINAL_PWM_SENT()
******************************************************************************************************/
void FINAL_PWM_SENT(int pwm_1  , int pwm_2 )
{

if(pwm_1<0 && pwm_2<0)      // MOVE BOTH MOTORS IN BACKWARDS DIRECTION 
{

pwm_1= map(constrain(pwm_1 ,-255, 255), 0, -255, 29, 255 ); // THE MINIMUM VALUE OF PWM IS SET TO 29 SO THAT BOT CAN REACT AND CORRCT IT TILT TO VERY SMALL ANGLE CHANGE AT STAEDY STATE 
pwm_2= map(constrain(pwm_2 ,-255, 255), 0, -255,  29, 255);


 analogWrite(EN_A , pwm_1 ) ; 
 digitalWrite(IN_1, HIGH);
 digitalWrite(IN_2, LOW);

 analogWrite(EN_B , pwm_2)  ; 
 digitalWrite(IN_3, LOW);
 digitalWrite(IN_4, HIGH);

}

else if(pwm_1>=0 && pwm_2>=0)     // MOVE BOTH MOTORS FORWARD DIRECTION 
{
pwm_1 =  map(constrain(pwm_1 ,-255, 255), 0, 255, 29, 255);
pwm_2 =  map(constrain(pwm_2 ,-255, 255), 0, 255, 29 , 255);

analogWrite(EN_A , pwm_1 ); 
digitalWrite(IN_1, LOW);
digitalWrite(IN_2, HIGH);

analogWrite(EN_B , pwm_2)  ; 

digitalWrite(IN_3, HIGH);
digitalWrite(IN_4, LOW);
 
}
}




/*********************************************************************************************
* Function Name : setup
* Input :  NONE
* Output:  NONE
* Logic :  TO INITALIZE ALL THE PARAMETERS ONCE 
* Example Call : setup() - CALLED INTERNALLY 
*********************************************************************************************/
void setup(){

    // PINMODE CONFIGURATION 
    pinMode(EN_A, OUTPUT);
    pinMode(EN_B, OUTPUT);
    pinMode(IN_1, OUTPUT);
    pinMode(IN_2, OUTPUT);
    pinMode(IN_3, OUTPUT);
    pinMode(IN_4, OUTPUT);

}




/*********************************************************************************************
* Function Name : loop
* Input :  NONE
* Output:  NONE
* Logic :  CALLS FINAL_PWM_SENT() REPEATEDLY
* Example Call : loop() - AUTOMATICALLY CALLED INTERNALLY
*********************************************************************************************/
void loop(){

FINAL_PWM_SENT( FINAL_PWM_SENT_TO_MOTOR_1 , FINAL_PWM_SENT_TO_MOTOR_2) ;         // THE FINAL PWM GOING TO THE MOTORS 

}